import fs from 'fs';
import path from 'path';

const rawEntries = [
  [1, "aptoide", "Uang Cepat - Pinjaman Duit Cair Tunai Dana Cepat", "Huang Bao"],
  [2, "aptoide", "Dana Siap - Pinjaman Uang Tunai Dana Cash", "GABRIEL RODRIGUEZ"],
  [3, "softonic", "Duit Happy - Pinjaman Online", "PT.Duit Happy Indonesia"],
  [4, "softonic", "Platform Pinjaman Online TaTa", "Resmy Technology"],
  [5, "softonic", "Pinjaman Uang- Online Kredit D", "Wu Mangg"],
  [6, "softonic", "Pinjaman Syariah Online Cepat", "Slides Dev"],
  [7, "softonic", "Dana Ribu - Pinjaman Online", "Dana Ribu"],
  [8, "softonic", "Kredit Rupiah-Pinjaman Dana", "ROBI SUGARA"],
  [9, "softonic", "KTA Gampang –Pinjaman Online Dana Kredit Tunai", "Rahmad Syarhan"],
  [10, "softonic", "Kilat Cicil - Pinjaman Dana", "Kilat Cicil Dev"],
  [11, "softonic", "Murni Pinjaman-Credito Pinjol", "ARELLANO TAFOLLA AGUSTIN"],
  [12, "softonic", "Pinjaman Angsuran Ty", "Muhamad Technology"],
  [13, "softonic", "Pinjol kilat modal KTP", "Xfourteendev"],
  [14, "softonic", "Tunaikan - pinjol masa kini", "Ange demu"],
  [15, "softonic", "Klik Kredit-Pinjaman Pinjol", "ROBI SUGARA"],
  [16, "softonic", "Dana Mudah-Pinjaman Cepat", "PT. Dana Mudah Indonesia"],
  [17, "softonic", "PINTAR KREDIT - PINJAMAN UANG ONLINE BUNGA RENDAH", "GIKA INDONESIA"],
  [18, "softonic", "Dana Fulus-Pinjama Cepat", "PT SEJAHTERA INTERNATIONAL INDONESIA"],
  [19, "apkpure", "Pinjam Uang – Pinjaman Online Cepat Cair", "Pinjam Uang Team"],
  [20, "apkpure", "Pinjaman Cepat Uang Teman Kredit Talangan Keuangan", "PT. Dana Segera Cair"],
  [21, "apkpure", "PinjamMudah", "Audrey Spittler"],
  [22, "apkpure", "Rupiah Plus - Pinjam Uang Langsung Cair", "PT.Arta Mandiri TBK"],
  [23, "apkpure", "SAKU KAMI – KTA online, pinjam cepat cair", "PT Karya Nusa Mandala"],
  [24, "apkpure", "Pinjam Uang - Tempat pinjaman tanpa jaminan online", "Meixin Global Fintech"],
  [25, "apkpure", "Pinjaman Uang Online - Kredit Cicilan Cepat Cair", "PT. Dinar Antam jaya"],
  [26, "apkpure", "Pinjaman Uang Tunai Cepat Kredit Tunai Dana Teman", "CosmikSemanggi"],
  [27, "aptoide", "DanaKu—Kredit Cepat Pinjaman Uang Online", "Eric"],
  [28, "aptoide", "Go Cash - Pinjaman Dana Tunai Online", "Pinjaman Online Uang Cepat Cepat: Go Cash"],
  [29, "softonic", "Cepet Dana-Pinjaman Cair Tunai", "uangcash210209"],
  [30, "softonic", "Easy Dana", "vivaylien"],
  [31, "softonic", "Dana Flow-Pinjama dana cepat", "PT SEJAHTERA INTERNATIONAL INDONESIA"],
  [32, "softonic", "Dana Darurat - Kredit Tunai", "PT.kecemerlangan Fintech Indonesia"],
  [33, "softonic", "Dana Dompet-Pinjaman Online", "Uang cepat"],
  [34, "softonic", "DANASUMO - PINJAMAN ONLINE CEPAT CAIR TERBARU", "PT. Easy Dana Indonesia"],
  [35, "softonic", "YOKOTO - PINJAMAN ONLINE LANGSUNG CAIR TERBARU", "Margo Developer"],
  [36, "softonic", "Rupiah Kasih - Dana Cepat", "PT.Rupiah Kasih Indonesia"],
  [37, "softonic", "Sinar Rpro - Pinjaman Dana", "Sinar Rupiah Nusantara"],
  [38, "softonic", "Pasar KTA - Pinjaman Uang Online Cepat Dana Cair", "PT Inspira Data Nusa"],
  [39, "softonic", "Pinjaman Tanpa Jaminan Rocket", "Hamdan Technology"],
  [40, "softonic", "Pinjaman Cepat Hhemat Waktu", "Shohel Technology"],
  [41, "softonic", "Pintar Cair Pinjaman 24jam", "Pintar Cair"],
  [42, "softonic", "Teman Uang", "Willhoite Nick"],
  [43, "softonic", "Cheetah-Pinjaman Cepat", "Cheetah Pinjaman Cepat"],
  [44, "softonic", "Cara Pinjaman Online Cair KTP", "NOV Tech."],
  [45, "softonic", "Rupiah Maju - Pinjaman dana tunai online cair", "PT Rupiah Maju"],
  [46, "aptoide", "Ada Dana", "Pinjam Cepat 66"],
  [47, "softonic", "Sentral Pinjaman - Pinjaman Digital", "Mega Central Finance"],
  [48, "softonic", "Pinjaman Cepat - Pinjaman Uang", "Dao Gu"],
  [49, "softonic", "Pinjaman Dana Uang", "Margo Developer"],
  [50, "softonic", "DuitKu-Pinjaman Online", "cashaman8"],
  [51, "softonic", "Kya-Pinjaman Online", "Vergara Manuel Zambrano"],
  [52, "softonic", "DanaKu-Pinjaman Online", "Uang cepat"],
  [53, "softonic", "Pinjaman Cepat Keluarga", "Rashed Technology"],
  [54, "softonic", "Pinjaman Amanah - Kredit", "perusahaan abadi dana"],
  [55, "softonic", "Tunai Kilat-Pinjaman Tunai", "Perusahaan Keuangan Anark"],
  [56, "softonic", "Tunai Kilat-Pinjaman Tunai", "Perusahaan Keuangan Anark"],
  [57, "softonic", "Tunai Pinjaman-Pinjaman Uang Tunai Dana Online", "Indah Maya Sari"],
  [58, "softonic", "Kredit Digital-Uang Tunai", "PT. Kreditsekali"],
  [59, "softonic", "Ada Tunai-Pinjaman Online", "Luis Alberto"],
  [60, "softonic", "Aplikasi Penghasil Uang Nyata", "Bankjo Finance"],
  [61, "softonic", "Pinjaman Hoki-Uang Online", "PT. Pinjaman Hoki Indonesia"],
  [62, "softonic", "Pinjaman Kilat - Tunai Mudah", "ESMIYATI"],
  [63, "softonic", "Pinjaman Tunai Wilmar", "Lourdes Mondejar"],
  [64, "softonic", "Dana Darurat - Layanan", "Fintech Company"],
  [65, "softonic", "Kotak Koin - Credit Dana Cepat", "PT Coco Digital Technology"],
  [66, "softonic", "Abadi Dana - Pinjaman Uang", "Pinjaman Digital"],
  [67, "softonic", "Dana Aman -Pinjaman Online Uang Tunai Bunga Rendah", "Dana Aman"],
  [68, "apk_cafe", "UANG BAHAGIA - PINJAM UANG DENGAN CEPAT", "saacSalvant"],
  [69, "apk_cafe", "PAHLAWAN PINJAMAN - PINJAMAN ONLINE AMAN DAN CEPAT", "Pahlawan Pinjaman"],
  [70, "apk_cafe", "CASHSAKU-PINJAMAN ONLINE CEPAT CAIR", "xin liu"],
  [71, "apk_cafe", "BUNGA DAHLIA-PINJAM ONLINE CASH DANA UANG", "Bunga Lotus"],
  [72, "apk_cafe", "PINJAM WALLET TUNAI CLUE", "Denim Market APP"],
  [73, "apk_cafe", "PINJAMAN ONLINE CEPAT LOAN PRESTAMO-CASH MONEY", "Cash Money creditloan"],
  [74, "apk_cafe", "RUMPUT LAUT - PINJAMAN UANG ONLINE KREDIT", "FinancialTechGroup"],
  [75, "apk_cafe", "PINTAR KREDIT - PINJAMAN UANG ONLINE BUNGA RENDAH", "Payindo"],
  [76, "softonic", "Conston Dana-Pinjaman Online", "Conston Dana-Pinjaman Online"],
  [77, "softonic", "Kredit Dompet-Pinjaman Dana", "PT Dana Mutiara Finansial Teknologi)"],
  [78, "softonic", "Dana Pratama - Pinjaman Online", "Dana Pratama"],
  [79, "softonic", "Abadi Dana - Dompet Bantuan", "Wonderland Tech"],
  [80, "softonic", "Cash Dana-Pinjaman Tunai Uang", "PT. Cash Dana Indonesia"],
  [81, "softonic", "Tunai Dana - Pinjaman Uang Tun", "He S huai"],
  [82, "softonic", "Hy Pinjam Uang:Pinjaman Tunai", "Gupta Technology"],
  [83, "softonic", "Dana Mutiara-Pinjaman Uang", "PT. Dana Mutiara Indonesia"],
  [84, "softonic", "Dana Mudah - Super Cash", "PT Tunai Cair Financial"],
  [91, "softonic", "Pinjam Dana - Pinjol Modal KTP", "Dev Denmark"],
  [92, "apkpure", "Dana Pribadi", "deisonposer"],
  [93, "apkpure", "Online Utang", "Sunprime Finance Inc."],
  [94, "apk_cafe", "DANASUMO - PINJAMAN ONLINE CEPAT CAIR TERBARU", "cesnehto group"],
  [95, "apk_cafe", "YOKOTO - PINJAMAN ONLINE LANGSUNG CAIR TERBARU", "cesnehto group"],
  [100, "apk_cafe", "PINJAM MULUS - 24 JAM CEPAT CAIR CUKUP KTP CEPAT", "cesnehto group"],
  [101, "apkpure", "Wall in - Pinjaman uang cepat", "Upson Trainor"],
  [102, "apkpure", "PAS DANA", "senag kali8"],
  [103, "apkpure", "Pasar KTA - Pinjaman Uang Online Cepat Dana Cair", "Tunai Wallet"],
  [104, "softonic", "Hello Duit - Dana Happy", "PT Hello Duit Lmt"],
  [105, "softonic", "Dana Cepat-Pinjaman Online", "Suchart Kaisariman"],
  [106, "softonic", "Uang Dana-Pinjaman tunai cepat", "Branches Studio"],
  [107, "softonic", "Dana Raja Online Cepat Aman", "PT Ruixiang International Indonesia"],
  [108, "softonic", "Pinjaman Amanah - Kredit", "Company Abadi Dana"],
  [109, "softonic", "Rupiah Nomplok-Pinjaman Duit", "PT Rupiah Nomplok Indonesia"],
  [110, "apk_cafe", "PinjamDisini (Ani Sa)", null],
  [111, "softonic", "Pinjaman Kilat - Tunai Mudah", "ESMIYATI"],
  [112, "softonic", "Kredit Pinjaman", "Michael Lee Pollard"],
  [113, "softonic", "Dana Darurat - Pinjaman Kredit", "PT Kecemerlangan Fintech Indonesia"],
  [146, "apk_cafe", "Kredit Money - Instant Loan", "Kredit Money"],
  [147, "apk_cafe", "Kissht Loan - Personal Money", "Play Oct India"],
  [148, "apk_cafe", "Credits Money", "Titan Kit"],
  [149, "apk_cafe", "Money Tank-Credit Cash Loan", "S ASIFA"],
  [165, "apk_cafe", "Credit Cash", "PanchartDev"],
  [166, "apk_cafe", "KasKita Tunai", "KellySend Maik"],
  [170, "aptoide", "DanaKu-Kredit Cepat Pinjaman Uang Online", "Eric"],
  [171, "apkpure", "iPinjaman", "Mohamed Abd Elwahied"],
  [172, "apk_cafe", "Optima - Pinjaman Uang Online", "PT ETI"],
  [173, "softonic", "Dana Cash Pinjaman Online Te", "Diana M.Mbori"],
  [174, "softonic", "Pinjaman dana cicil", "Margo"],
  [175, "apkpure", "Bos Uang Rupiah - Pinjaman Dana Cepat", "Bos Uang"],
  [176, "apkpure", "Petir-Uang", "Kapoor Boat"],
  [177, "softonic", "Dana Cepat-Pinjaman Online", "DanaCicil Pro"],
  [178, "softonic", "Dana Cicil Online-Pinjam Cepat", "DanaCicil Pro"],
  [179, "softonic", "Dana Kita - KAT Cepat Online", "PT Wanbaolai Internasional Indonesia"],
  [180, "softonic", "HappyDana - Dana Cepat", "HD Co. Ltd."],
  [181, "softonic", "Dana Pro - PINJAMAN CEPAT", "PT Hongxin International Indonesia"],
  [185, "apkcombo", "GOCAP CEPAT - Pinjem Duit Gak Pake Ribet", "Melempar Bantuan"],
  [186, "apkcombo", "Dana Kita", "Coy Lee"],
  [193, "apkcombo", "Uang Siap - Talangan Dana Tanpa Agunan", "PT Tangguh Tanggap Aguna"],
  [194, "apkcombo", "Dana Pribadi - Dana Cepat Online", "Jennifer Tinnes"],
  [195, "apkcombo", "DanaKu", "Qworks"],
  [196, "apkcombo", "Dapat Rupiah-easy cash ktedit online", "Alighor bani"],
  [203, "softonic", "Pinjaman Online - Kilat Mudah", "Kesiapsiagaan7701"],
  [204, "apkcombo", "Dana online - Kedatangan cepat", "Amelia Byrd"],
  [205, "apkcombo", "Dolang", "Uang Market"],
  [206, "apkcombo", "Saku Kita", "Sakukita Cermat"],
  [207, "apkcombo", "Saku mimpi", "werasdzxc"],
  [208, "apkcombo", "Ticket Vip", "Losif kagan"],
  [209, "apkcombo", "Daun Hijau", "Wayland Tyle"],
  [210, "apkcombo", "Saku peri", "Nedhua"],
  [211, "apkcombo", "Saku Pinjaman", "onlinepinjam"],
  [212, "softonic", "Abadi Dana - dompet", "company abadi dana"],
  [213, "softonic", "Uang Pinjam-Pinjam Dana Cepat", "Uang Pinjam MyTunai"],
  [214, "softonic", "Dompet Kaya-Dana Credit Online", "PT Wanbaolai International Indonesia"],
  [215, "softonic", "Neo Cash - Pinjaman dana tunai", "keep wang"],
  [216, "softonic", "Dana Cepat - Pinjaman Uang Dana", "Jujube Studio"],
  [217, "softonic", "Dana Kejayaan - Uang Online", "PT Dana Kejayaan Teknologi"],
  [218, "softonic", "Dana Plus", "DanaPluss"],
  [219, "softonic", "Pinjaman Duit KTA Online", "Pinjaman Duit"],
  [220, "softonic", "Uang Mudah - ayo pinjam", "PT.Uang Mudah Indonesia"],
  [221, "softonic", "Pinjam Me-Pinjaman uang online", "LAYANAN KEUANGAN EFFICACY PRIVATE LIMITED"],
  [222, "softonic", "Dana Mudah - Super Cash", "PT Tunai Cair Financial"],
  [223, "softonic", "Yok Cicil - Simulasi Pinjaman", "PT Dana Kredit Sosial"],
  [224, "softonic", "Tunai Cepat-Pinjaman Uang Dana", "Jujube Studio"],
  [225, "softonic", "Dana Dana", "Dana Dana pro"],
  [226, "softonic", "Lucky Uang - Pinjam Uang Murah", "PT. Lucky Uang"],
  [227, "softonic", "Duit Gesit - Pinjam Gesit Tanpa Ribet", "George S Taylor"],
  [228, "softonic", "Petir Uang - Pinjaman Uang", "PT Petir Uang Finansindo"],
  [229, "softonic", "Uang Mudah - Pinjam Dana Cepat", "Huang Bao"],
  [230, "softonic", "Dana Pro - Cepat Uang Dana", "PT KEBIJAKSANAAN INTERNATIONAL INDONESIA"],
  [231, "softonic", "Dana GoKredit Cepat", "Pinjaman Amanah"],
  [247, "softonic", "Rupiah Now-Pinjama Dana Online", "Pt Dia Ying International Indonesia"],
  [248, "softonic", "Uang Aman-Pinjaman Dana", "PT. Uang Aman Indonesia"],
  [249, "softonic", "Dana Uang-pinjam online", "PERUSAHAAN PINJAMAN DAGDAKS"],
  [258, "softonic", "Uang Tunai - Pinjaman Uang Cash Dana Cair Cepat", "huang yong s"],
  [266, "softonic", "Dana Baguslah - murni online", "PT.Dana Baguslah Indonesia"],
  [267, "softonic", "Ayo Uang - Pinjaman online pribadi", "Milo Spencer"],
  [268, "softonic", "Black Box : Pinjam Uang", "Black Box Technologies L.l.c"],
  [277, "softonic", "Abadi Dana - dompet", "company abadi dana"],
  [278, "softonic", "Fast Kredit Indonesia", "Fast Kredit Nusantara"],
  [279, "softonic", "KTA Bijak - Kredit Pinjaman", "Mochamad Gatot Susanto"],
  [280, "softonic", "Dana Kilat - Pinjaman Online Dana Tunai Aman", "LuckyNine Apps"],
  [281, "softonic", "Dana Uang-pinjam online", "DAGDAKS LENDING CORPORATION"],
  [282, "softonic", "Cepat Uang - Pinjaman kredit", "BAIRAVI FINANCE PRIVATE LIMITED"],
  [283, "softonic", "Cepat Uang", "pbpbpbpbpb"],
  [284, "softonic", "Do-It Pinjaman Uang Online", "Glotech Prima Vista"],
  [285, "softonic", "Dana Uang-pinjam online", "DAGDAKS LENDING CORPORATION"],
  [286, "softonic", "Dana Uang-pinjam online", "DAGDAKS LENDING CORPORATION"],
  [287, "softonic", "Dana Wallet - Pinjam Online", "VISMART LENDING CORPORATION"],
  [288, "apkpure", "Layar Pinjam", "Becker Vergie"],
  [289, "apkpure", "Pinjaman Pertama", "Ayo Credo Indonesia"],
  [290, "apk_cafe", "Pinjaman cepat - Pinjaman Uang Tunai Cepat", "larry lending"],
  [291, "apk_cafe", "Instant Personal Loan App Online Loan - LoanBean", "Loan & Finance service"],
  [292, "softonic", "DanaCair:Pinjam Cash Cepat", "LEXICON FINANCE LIMITED"],
  [293, "softonic", "DanaFull Pinjam - loan", "PT Danafull Finance Indonesia"],
  [294, "softonic", "DanaKilat-Pinjam Kredit Cash", "SIDHANT FINANCIAL SERVICES LIMITED"],
  [295, "softonic", "Dompet Mudah - Pinjam Cepat", "PT.Dompet Mudah"],
  [296, "softonic", "PAS DANA Cair Kapan Saja Pas Kamu Butuh", "senag kali8"],
  [297, "softonic", "Dana Bull - Dana Tunai Cair", "PT. DANA BULL"],
  [301, "softonic", "Tunai Sayang-Cepat Uang", "PT. Tunai Sayang Indonesia"],
  [302, "softonic", "Fulus Mas - Pinjaman Uang Tunai Cepat", "Metin Bas"],
  [303, "softonic", "Lucky Uang - Pinjam Uang Murah", "PT. Lucky Uang"],
  [304, "softonic", "Modal Kilat - Pinjaman Uang", "ASMUNTI BOI"],
  [305, "softonic", "Petir Uang - Pinjaman Uang", "PT Petir Uang Finansindo"],
  [306, "softonic", "Pinjaman Dana Uang", "Margo Developer"],
  [307, "softonic", "Rupiah Nomplok- Pinjaman Duit", "PT.Rupiah Nomplok Indonesia"],
  [308, "softonic", "Rupiah Saku - Pinjaman Kredit", "PT Rupiah Saku"],
  [309, "softonic", "Kredit Good - Pinjaman Online", "PT.Kredit Good Indonesia"],
  [310, "apkpure", "Kelinci Lompat- Pinjam Uang Tunai mudah Cepat Cair", "Nico Syan"],
  [311, "apkpure", "Tunai Plaza-Uang Kredit Pinjaman dana tunai online", "Berneice Masin"],
  [312, "apkpure", "TUNAI KAMI", "NUSANTARA"],
  [313, "apkpure", "Kita Patungan - Pinjaman uang tunai tanpa jaminan", "Fajar Rhamdhani"],
  [314, "softonic", "Achilles Cepat- Pinjaman Dana Tunai Cepat Cair", "UR Cashbank"],
  [315, "softonic", "Cepet Dana-Pinjaman Cair Tunai", "uangcash210209"],
  [324, "softonic", "Dana mudah Cicil-PINJAMAN", "Margo Developer"],
  [325, "softonic", "Dana Dompet-Pinjaman Online", "Uang cepat"],
  [326, "softonic", "Easy Dana-Pinjaman Tunai Uang", "PT. Easy Dana Indonesia"],
  [327, "softonic", "TunaiKita Pinjaman Uang Tunai Online Dana Cepat", "PT. Digital Tunai Kita"],
  [328, "softonic", "Kredit Rupiah-Pinjaman Dana", "ROBI SUGARA"],
  [329, "softonic", "Kilat Cicil - Pinjaman Dana", "Kilat Cicil Dev"],
  [330, "softonic", "Abadi Dana - Pinjaman Uang", "Pinjaman Digital"],
  [331, "softonic", "Dana Cash Pinjaman Online Te", "Diana M.Mbori"],
  [349, "softonic", "Ayo: Pinjaman Tanpa Agunan", "Ayo: Pinjaman Tanpa Agunan"],
  [350, "softonic", "Dana Cash Pinjaman Online Te", "Diana M.Mbori"],
  [351, "softonic", "Pinjaman Angsuran Paus Biru", "Laurados Santosfranca"],
  [352, "softonic", "Ve-lot Online:Pinjaman Pnstan", "Namg Pociten"],
  [353, "softonic", "Cash Now Pinjaman Terpercaya", "viapramudita"],
  [354, "softonic", "PINJAMAN PEDIA - Tempat Pinjaman Uang Tunai Dana", "PT . AIMARS TECHNOLOGY INDONESIA"],
  [355, "softonic", "Kantong Sahabat-Pinjam Uang Tunai Kredit Dana Cash", "Gold Park Like"],
  [356, "softonic", "Dana Mudah-Pinjaman Cepat", "PT. Dana Mudah Indonesia"],
  [357, "softonic", "Dana Cepat-Pinjaman Online", "DanaCicil Pro"],
  [358, "softonic", "SINAR RUPIAH", "Sinar Rupiah Nusantara"],
  [359, "softonic", "Rupiah Maju - Pinjaman dana tunai online cair", "PT Rupiah Maju"],
  [360, "softonic", "Danafix - Pinjaman Uang Online Kredit Tunai Cepat", "PT. DANAFIX ONLINE INDONESIA"],
  [372, "softonic", "Dana Mudah - Super Cash", "PT Tunai Cair Financial"],
  [373, "softonic", "Uang Aman-Pinjaman Dana", "PT. Uang Aman Indonesia"],
  [374, "softonic", "Hello Duit - Dana Happy", "PT Hello Duit Lmt"],
  [375, "softonic", "Mini Cash - Pinjam Cepat", "personal credit"],
  [376, "softonic", "Kredit Easy - Pinjam Dana Uang Cepat Online", "STACY FRANCIS"],
  [377, "softonic", "Pinjaman Amanah Kredit Cepat", "Pinjaman Amanah"],
  [378, "softonic", "Ayo Uang - Pinjaman online Pribadi APK", "Milo Spencer"],
  [379, "softonic", "Dana mudah Cicil - PINJAMAN", "Margo"],
  [380, "softonic", "PinjamanKu - Solusi Pintar Kebutuhan Finansial", "Nur Aida"],
  [381, "apkcombo", "Petir-Uang", "Kapoor Boat"],
  [382, "apkcombo", "Raja Uang-Tempat Pinjam uang Online Tanpa Jaminan", "Donella Strout"],
  [383, "apkcombo", "Oklik Cash-Pinjaman Cepat Uang Tunai", "RAINBOWCASH.PH LENDING CORP."],
  [384, "softonic", "Neo Cash - Pinjaman dana tunai", "keep wang"],
  [385, "softonic", "Rupiah Kas - Pinjaman Online", "VINZOL CAPITAL AND FINANCE LIMITED"],
  [386, "softonic", "Witop-Pinjaman Cepat", "Silva Dajsoe Riogord"],
  [389, "softonic", "Dana Me - Pinjaman uang online", "MINDEX FINCAP PRIVATE LIMITED"],
  [390, "softonic", "Fast Kredit Indonesia", "Fast Kredit Nusantara"],
  [391, "softonic", "KTA Bijak - Kredit Pinjaman APK", "Mochamad Gatot Susanto"],
  [392, "softonic", "Pinjaman Kelinci - KTA Terbaik", "Sarmadi"],
  [393, "softonic", "Platform Pinjaman Online XOT", "Malek Technology"],
  [394, "apkpure", "Dana Cepat - Pinjam Uang Langsung Cair", "PT Arta Mandiri TBK"],
  [395, "apkpure", "Aku Cepat", "John Austin)"],
  [396, "apkpure", "Banana Duit-Uang Pinjam Cepat Online", "Vibhore Lauren"],
  [397, "apkpure", "Cepat uang-pinjam mudah uang online duit", "Rodriguez TS"],
  [398, "apkpure", "Pinjam Aja - Pinjaman Online Mudah Dan Cepat", "Alonso Sidwell)"],
  [409, "softonic", "Indonesia Uang-Pinjaman Aman", "SANCHEZ MARTINEZ MARIA FERNANDA"],
  [410, "softonic", "Pinjaman PertamaUang Cepat - Pinjaman Duit Cai", "Huang Bao"],
  [411, "softonic", "Swan Pinjaman Tunai Pribadi", "Ninad Technology"],
  [419, "softonic", "Pinjam Uang-Uang Kilat", "Linnaeus Pendanaan Teknologi"],
  [420, "softonic", "Super Rupiah - Aman dan Cepat", "PT.SUPER RUPIAH INDONESIA"],
  [421, "softonic", "Tunai Instan", "Tunai Harian Lite"],
  [422, "softonic", "Aman Rupiah-Pinjaman Online", "Luis Alberto)"],
  [423, "softonic", "Lucky Uang - Pinjam Uang Murah", "PT. Lucky Uang)"],
  [424, "softonic", "Pinjam Mudah - Uang Onlin", "SYUELU"],
  [433, "softonic", "OKP2P - Pinjaman ok Layanan", "PT. OKE PTOP INDONESIA)"],
  [434, "softonic", "DuitKu-Pinjaman Online", "cashaman8"],
  [435, "softonic", "DanaKu-Pinjaman Online", "Uang Cepat"],
  [436, "softonic", "Pinjaman Tunai BAA", "Jhosel Valdiviezo Coronel"],
  [437, "softonic", "Dompet Mudah - Pinjam Cepat", "PT.Dompet Mudah)"],
  [438, "softonic", "Indonesia Uang-Pinjaman Aman", "SANCHEZ MARTINEZ MARIA FERNANDA"],
  [439, "softonic", "Kelinci Lompat - Pinjam Uang Tunai Mudah Cepat Cair", "Nico Syan"],
  [440, "softonic", "Dana Pinjam - Kredit Pinjam Dana Tunai Online Cepat", "Sawayn Ervin"],
  [441, "softonic", "Duit Happy - Pinjaman Online", "PT.Duit Happy Indonesia"],
  [442, "softonic", "Tunai Kilat-Pinjaman Tunai", "Perusahaan Keuangan Anark"],
  [443, "softonic", "Uang Pinjam-Pinjam Dana Cepat APK", "Uang Pinjam MyTunai"],
  [444, "softonic", "Uang Mudah - Pinjam Dana Cepat", "Huang Bao"],
  [445, "softonic", "Uang Dana-Pinjaman tunai cepat", "Branches Studio"],
  [446, "softonic", "Cepat oke - Pinjol yang cairnya paling cepat", "PT. Surya Bermuda)"],
  [447, "softonic", "Opsna Cash - Aplikasi Cash Tunai Cepat Cair", "Jesús Sánchez Moreno"],
  [448, "softonic", "Dana Cepat-Pinjaman Online", "DanaCicil Pro"],
  [449, "softonic", "Dana Aman - Pinjaman Online Uang Tunai Bunga Rendah", "Dana Aman"],
  [450, "softonic", "Tunai Pinjaman-Pinjaman Uang Tunai Dana Online", "Indah Maya Sari"],
  [451, "softonic", "Cash Planet - Online Loan App", "ASOMI FINANCE PRIVATE LIMITED"],
  [452, "softonic", "Dana Mudah - Super Cash", "PT Tunai Cair Financial"],
  [453, "softonic", "Tunai Cepat-Pinjaman Uang Dana", "Jujube Studio"],
  [454, "softonic", "Rupiah Mudah - Pinjam Dana", "BUENO LENDING INVESTOR INC."],
  [455, "softonic", "Cepat Cash - pinjam online", "GIRINANDINI MERCANTILE PRIVATE LIMITED)"],
  [456, "softonic", "258-Pinjaman Online Cepat", "Riveros Carlosjose"],
  [457, "softonic", "Modal Kilat - Pinjaman Uang APK", "ASMUNTI BOI"],
  [458, "softonic", "Pinjaman Amanah Kredit Cepat", "Pinjaman Amanah"],
  [459, "softonic", "Tunai Kilat - Pinjaman Cepat", "Perusahaan Keuangan Anark"],
  [460, "softonic", "Dana Mantul - pinjam uang lebih mudah", "PT. Permata Maya Nusantara"],
  [461, "softonic", "Dana Cash Pinjaman Online Te", "Diana M.Mbori"],
  [462, "softonic", "Lucky Uang - Pinjam Uang Murah", "PT. Lucky Uang"],
  [463, "softonic", "Dana Cepat-Pinjaman Online", "Suchart Kaisariman"],
  [474, "softonic", "DanaKu- Pinjaman Online", "Uang cepat"],
  [475, "softonic", "Klik Kredit-Pinjaman Pinjol", "ROBI SUGARA"],
  [476, "softonic", "PinjamanLincah - Pinjam Uang Tunai Cepat", "Bustos Casiglia"],
  [477, "softonic", "TUNAIKU Cepat - Pinjam Uang Cepat Mudah", "Reef Tech"],
  [478, "softonic", "PerluDana - Piajam uang tunai tanpa jaminan cepat", "Kathy.Rios"],
  [479, "softonic", "Dana Cepat - Pinjaman Uang Dana", "Jujube Studio"],
  [480, "softonic", "Dana Dana - Pinjaman Online", "STERLING MEGABUCKS PRIVATE LIMITED)"],
  [481, "softonic", "Dana Cepat-Pinjaman Online", "Suchart Kaisariman"],
  [494, "softonic", "Pinjaman online WOW", "Abdul Technology"],
  [495, "softonic", "Pinjaman Syariah Online Cepat", "Slides Dev"],
  [496, "softonic", "Pinjaman Tanpa Agunan FTR", "Limarijose Hormazabal Andres"],
  [497, "softonic", "Pinjaman Tunai BAA", "Jhosel Valdiviezo Coronel"],
  [498, "softonic", "Pinjaman Tunai Wilmar", "Lourdes Mondejar"],
  [499, "softonic", "Pinjamindo - Pinjaman Uang Onl APK", "PT. Serba Digital Teknologi"],
  [500, "softonic", "Pinjamnow", "CashQu"],
  [501, "softonic", "Dana Darurat - Pinjaman Kredit", "PT.kecemerlangan Fintech Indonesia"],
  [502, "softonic", "Cantik Dana - Pinjaman nyaman", "PT.Cantik Dana Indonesia"],
  [503, "softonic", "Cash Aku-pinjaman kredit uang", "PT Cash Aku Indonesia"],
  [504, "softonic", "KreditKaya-pinjaman online", "QUANTUM HOLDINGS INC."],
  [505, "softonic", "KTA Gampang - Pinjaman Online Dana Kredit Tunai", "Rahmad Syarhan"],
  [506, "softonic", "Kya-Pinjaman Online", "Vergara Manuel Zambrano"],
  [507, "softonic", "Babox - Pinjaman Online", "Ha Danh Tien"],
  [508, "softonic", "Cair 2 Juta Pinjam Cepat Tips", "FinTechno Ltd"],
  [509, "softonic", "Dana Info - Pinjaman Dana Onli", "Info Kredit Pinjaman Online"],
  [510, "softonic", "Dana Joy-Pinjama dana online", "Koperasi Simpan Pinjam Citra Abadi Jawa Timur"],
  [511, "softonic", "Dana Me - Pinjaman uang online", "Mindex Fincap Private Limited"],
  [512, "softonic", "Dana Now-Dana Credit Online", "Prime Caplease Private Limited"],
  [513, "softonic", "Dana Panas - Pinjaman Online", "Koperasi Simpan Pinjam Dana Senja Indonesia"],
  [514, "softonic", "Dana Pro - Cepat Uang Dana", "Pt Kebijaksanaan International Indonesia"],
  [515, "softonic", "Dana Saya - Pinjaman online", "Prime Caplease Private Limited"],
  [516, "softonic", "Danafix - Pinjaman Online Uang", "Danafix Online Indonesia"],
  [517, "softonic", "DanaMu Pinjaman Online FAQ", "Jennie Dev"],
  [518, "softonic", "DuitKu - Pinjaman Online", "Cashaman8"],
  [519, "softonic", "Cahir Kilat OJK Pinj4m Guide", "Arh Development"],
  [520, "softonic", "Pinjol 500Ribu Cair Info", "Team Gass"],
  [521, "softonic", "Pinjol 24jam Cepat Cair Hints", "Jumuahdev.Online"],
  [522, "softonic", "Tunai Swift - Pinjaman Online", "Growth Well Finlease Private Limited"],
  [523, "softonic", "Dana Ekspres - Pinjaman Online", "Jay Dee Ess Leasing Company Private Limited"],
  [524, "softonic", "Fast Pinjam - Pinjaman Online", "Baba Basuki Commercial Private Limited"],
  [525, "softonic", "Pinjaman Online Terbaru Hint APK", "Win Digital Khatulistiwa"],
  [526, "softonic", "Cepat Uang - Pinjaman kredit", "Bairavi Finance Private Limite"],
  [527, "softonic", "Saku Dompet - Pinjaman Online", "Gagalbhai Investments Private Limited"],
  [528, "softonic", "DanaKami : Pinjaman Uang", "Anshika Investments Private Limited"],
  [529, "softonic", "Tunai Kaya - Pinjaman kredit", "Supra Trafin Private Limited"],
  [530, "softonic", "DanaPlus-Pinjaman Online", "Turbopower Viet Nam Company Limited"],
  [531, "softonic", "DanaPintar-Pinjaman Dana", "Kan Viet Nam Company Limited"],
  [532, "softonic", "MudahUang - pinjaman online", "Suguna Fincorp Private Limited"],
  [533, "softonic", "AdaCepat - Pinjaman Dana", "Julina Paulin"],
  [534, "softonic", "Uang Kilat - Pinjaman Dana", "Ilocandia Fast Cash Corporation"],
  [535, "softonic", "Rupiah Kilat - Pinjaman Online", "Ruchika Growth Fund Private Limited"],
  [536, "softonic", "Kilat Cash - Uang Cash Online", "Calcutta Multimax Private Limited"],
  [537, "softonic", "Dana Instan - Dana Online App", "Dhanpaatra Capital Private Limited"],
  [538, "softonic", "Pinjaman Uang- Online Kredit", "Wu Mangga"],
  [539, "softonic", "Cash Advance Payday Advance APK", "Sanrus Inc"],
  [540, "softonic", "Cash To U", "Newmore Company Limited"],
  [541, "softonic", "CashBox Pro", "Smart-Tech Electro-Industrial Systems Inc.)"],
  [542, "softonic", "CashSumber - Pinjaman Online", "Plaza Fincap Private Limited"],
  [543, "softonic", "Cepat Cash - pinjam online", "Girinandini Mercantile Private Limited"],
  [544, "softonic", "Tunai Flexi - pinjaman online", "Brightskies Technologies Sae"],
  [545, "softonic", "Tunai Swift - Pinjaman Online", "Growth Well Finlease Private Limited"],
  [546, "softonic", "TuYo Cash", "Karla Igrecia"],
  [547, "softonic", "Uang Cair - Pinjaman Dana", "Madhuban Fincare Private Limited"],
  [548, "softonic", "Uang Easy - Dana Online App", "Calicut Mercantile Finance Limited"],
  [549, "softonic", "Pinjam Murah - Pinjaman Online", "Ankit Financial Services Private Limited"],
  [550, "softonic", "CashMagnet - Pinjaman Online", "Vikhyat Securities Private Limited"],
  [551, "softonic", "MoneyClub - Pinjaman Online", "Gokulesh Commercial Private Limited"],
  [552, "softonic", "Retwets - Pinjaman Online", "Sajid Rehman"],
  [553, "softonic", "DanaTunai - Pinjaman Online", "Chorsiya Finvest Private Limited"],
  [554, "softonic", "Uang Kilat", "Wa Eye"],
  [555, "softonic", "Pinjam Uang-Uang Kilat", "Linnaeus Pendanaan Teknologi"],
  [556, "softonic", "Modal Kilat - Pinjaman Uang APK", "Asmunti Boi"],
  [557, "softonic", "Duit Sayang-Kredit Uang Kilat", "Pt.Duit Sayang Indonesia"],
  [558, "softonic", "Tunai Kita - Pinjam Uang Cepat Kilat dan Mudah", "Pack Tech"],
  [559, "softonic", "Dana Cepat - Pinjaman Online", "Koperasi Simpan Pinjam Pulau Bidadari Indonesia"],
  [560, "softonic", "Fast Pinjam - Pinjaman Online", "Baba Basuki Commercial Private Limited"],
  [561, "softonic", "Rupiah Kas - Pinjaman Online", "Vinzol Capital And Finance Limited"],
  [562, "softonic", "Cicil Cepat - pinjaman online", "Hanurang Mercantiles Private Limited"],
  [563, "softonic", "DanaRupiah - Pinjaman Online", "Kalkut Vinimay Private Limited"],
  [564, "softonic", "Dana Rakyat Pinjam online tips", "Denim Market App"],
  [565, "softonic", "Dana Cash - Pinjol OJK guide", "Novembre Craft"],
  [566, "softonic", "Pinjam Dana Tanpa KTP App Info", "Apps Digitalize"],
  [567, "softonic", "Rupiah Plus Pinjaman-Clue", "Ldway"],
  [568, "softonic", "Rupiah Cash Cash Pro", "Rupiah Cash Ksp"],
  [569, "softonic", "Rupiah Amanah Uang Mudah APK", "Hett"],
  [570, "softonic", "DearRupiah - Kredit Uang Kilat", "PT.Money Cepat Indonesia"],
  [571, "softonic", "Dompet Emas Pinjama uang cepat", "Dompet Emas"],
  [572, "softonic", "Kredit Digital - Uang Kilat", "PT.Kreditsekali"],
  [573, "softonic", "Kredit Berlian - Pinjaman Uang", "PT.Kredit Berlian Indonesia"],
  [574, "softonic", "Lucky Uang - Pinjam Uang Murah", "PT. Lucky Uang"],
  [575, "softonic", "CePinjam - Pinjam Online Cepat", "Start Point For Call Center"],
  [576, "softonic", "Sarung Sakti -Tanpa KTP Clue", "Tor Labs"],
  [577, "softonic", "Naga Dana Pinjaman Advice", "Tor Labs"],
  [578, "softonic", "Pinjaman Cepat - Pinjaman Uang", "Dao Gu"],
  [579, "softonic", "Pinjam Cepat - Pinjam uang tunai tanpa jaminan cepat", "Aleshia McKinnon"],
  [580, "softonic", "D-duit pinjaman uang cepat", "Dasgupta Charles.rice"],
  [581, "softonic", "Dompet emas pinjama uang cepat", "Dompet emas"],
  [582, "softonic", "Pinjaman Uang - Tunai Dana Cepat", "Branches Studio"],
  [587, "softonic", "Cepat Kas - Pinjam Online", "Lakshmi Narsimha Finbiz Limited"],
  [588, "softonic", "KreditKaya-pinjaman online", "Quantum Holdings Inc"],
  [602, "softonic", "Dana Uang - Pinjam Online", "DAGDAKS LENDING CORPORATION"],
  [603, "softonic", "Tunai Instan - Dana Online App", "DAGA ENTRADE PRIVATE LIMITED"],
  [604, "softonic", "Dana Dana - Pinjaman Online", "STERLING MEGABUCKS PRIVATE LIMITED"],
  [605, "softonic", "Dana Now - Dana Credit Online", "KOPERASI SIMPAN PINJAM DANA SENJA INDONESIA"],
  [606, "softonic", "Dana Teratas - Dana Cepat Kredit", "PRINCEP TRADE AND FINANCE PRIVATE LIMITED"],
  [629, "softonic", "Pinjaman Online - Kilat Mudah", "Kesiapsiagaan7701"],
  [630, "softonic", "DearRupiah - Kredit Uang Kilat", "PT.Money Cepat Indonesia"],
  [631, "softonic", "Kantong Sukses - Pinjam Uang Tunai Rupiah Cepat", "Kantong Kilat"],
  [632, "softonic", "Pinjam Yuk - Pinjam Uang Kilat", "Solution Inc Developer"],
  [633, "softonic", "Kredit Digital - Uang Kilat", "PT.Kreditsekali | Program Lainnya (3)"],
  [659, "softonic", "Dana Instan - Dana Online App", "Dhanpaatra Capital Private Limited"],
  [660, "softonic", "Dana Fleksibel - Dana Online App", "JAIKAPEESH CAPITAL PRIVATE LIMITED"],
  [661, "softonic", "InstanRupiah - Dana Online", "MEGHANA CORPORATE PRIVATE LIMITED"],
  [662, "softonic", "Rupiah Kami - Pinjaman Dana", "CALLIGRAPHY LENDING INC"],
  [663, "softonic", "Halo Dana - Pinjaman Online", "SRIDHAR FINVEST LIMITED"],
  [664, "softonic", "Easy Dana - Pinjaman Online", "KHAZANA TRADELINKS PRIVATE LIMITED"],
  [665, "softonic", "Dana Saya - Pinjaman Online", "PRIME CAPLIASE PRIVATE LIMITED"],
  [666, "softonic", "Dana Baru - Pinjaman Pribadi", "JEWEL STRIPS PRIVATE LIMITED"],
  [667, "softonic", "Pinjam Ceria - Pinjaman Online", "SHANDYA FINANCE LIMITED"],
  [668, "softonic", "Pinjam Nyaman - Dana Cepat", "ASAMI FARMER FINANCE PRIVATE LIMITED"],
  [669, "softonic", "Koperasi Simpan Pinjam APK", "PT Sinar Teknologi Retailindo"],
  [670, "softonic", "Uang Mudah - Ayo Pinjam", "PT Uang Mudah Indonesia"],
  [671, "softonic", "Pinjam Murah - Pinjaman Online", "ANKIT FINANCIAL SERVICE LIMITED"],
  [672, "softonic", "New Cash - Pinjam Uang Kredit Dana Tunai", "Resolusiweb Developer"],
  [673, "softonic", "Cara Pinjam Saldo Dana APK", "TUNAY"],
  [674, "softonic", "Pinjam 3jt Cicil 40 Bulan Hint APK", "Apps Digitalize | More Programs"],
  [675, "softonic", "Tips Dana Rakyat Pinjam Online", "Babil Farisi"],
  [679, "softonic", "Dana Flexi - Uang Cepat", "The Hi-tech Gears Limited"],
  [680, "softonic", "DanaMitra - Pinjaman Dana Cepat", "Agung Raya"],
  [681, "softonic", "Dana Pintar: Pinjaman Cepat", "I.n.t Netlink Technologies Llc"],
  [682, "softonic", "Doku Cepat - Pinjaman Dana", "MUTHALAGU FINANCE PRIVATE LIMITED"],
  [683, "softonic", "Pinjam Nyaman - Dana Cepat", "ASAMI FARMER FINANCE PRIVATE LIMITED"],
  [684, "softonic", "Dana Kredit Uang Online Cash", "Combine Overseas Limited"],
  [685, "softonic", "KitaRupiah", "Indian Aviotronics A Division of DMG Finance Investments"],
  [686, "softonic", "Dompet Pulsa-Cepat Cash Online", "ASSETS FINANCE PRIVATE LIMITED"],
  [687, "softonic", "Cash Dana - Pinjaman Uang Tunai Dana Cepat Cair", "Zeli"],
  [688, "softonic", "Pintar Cair Pinjaman 24jam", "Pintar Cair"],
  [689, "softonic", "Aman Rupiah-Pinjaman Online", "LUIS ALBERTO"],
  [690, "softonic", "Achilles Cepat - Pinjaman Dana Tunai cepat cair", "Ur Cashbank"],
  [691, "softonic", "Pinjol 600rb Cepat Cair Info", "Kucai"],
  [692, "softonic", "Pinjol Cepat Cair Aman Tips", "Pinjol Tech Helper"],
  [693, "softonic", "Tunai Instan", "Tunai Harian Lite"],
  [694, "softonic", "Uang Cepat - Mudah Pinjaman Uang Tunai Online", "Jeanetta Sellers"],
  [695, "softonic", "DanaSegera - Pinjaman Uang Dana Tunai Online Cepat APK", "KSP Dana Mitra Sejahtera Abadi"],
  [696, "softonic", "Neo Cash - Pinjaman Dana Tunai", "keep wang"],
  [697, "softonic", "Kantong Sahabat - Pinjam Uang Tunai Kredit Dana Cash", "Gold Park Like"],
  [698, "softonic", "Saya Modalin - Pinjaman Rupiah Uang Tunai Dana Idr", "PT. MINITECH FINANCE INDONESIA"],
  [699, "softonic", "Saku Tunai", "donaldmay4928"],
  [700, "softonic", "Rupiah Petir - Pinjam Uang Tunai Kredit Dana Cash", "Landi CONWELL"],
  [701, "softonic", "Rupiah Plus Pinjaman - Clue", "LDWay"],
  [702, "softonic", "Duit panas-pinjaman online", "KOPERASI SIMPAN PINJAM IDA WELAS RASA"],
  [703, "softonic", "Kredit Easy-Pinjam Dana Uang Cepat Online APK", "STACY FRANCIS"],
  [704, "softonic", "apelbox - dana dengan cepat", "Crosby Graza"],
  [705, "softonic", "Dana Cicil Online - Pinjam Cepat", "DanaCicil Pro"],
  [795, "website", "Ponsel Duit", null],
  [796, "sfile", "Ponsel Duit", null],
  [797, "app_store", "SwapGo", null],
  [798, "website", "Ponsel Duit", null],
  [799, "apkpure", "Tunai Cash Pinjaman Online Tip", null],
  [800, "website", "Gandeng : Pinjaman Rupiah Mudah", null],
  [801, "website", "Dana Go - Uang Pundi", null],
  [802, "website", "Dana Rupiah Loan", null],
  [803, "website", "Pinjamindo", null],
  [804, "website", "5 KREDIT PINJAM", null],
  [805, "website", "KREDIT KILAT", null],
  [806, "website", "UangMe", null],
  [807, "website", "RUPIAH KAS", null],
  [808, "website", "SOLUSI DANA", null],
  [809, "sfile", "Duit Nomplok", null],
  [810, "softonic", "TunaiKita Pinjaman Uang Tunai Online Dana Cepat", null],
  [811, "app_store", "Touang - Easy Moyer", null],
  [812, "google_play", "So Easy", null],
  [813, "google_play", "Pinjam Fun - Bagikan Aplikasi", null],
  [814, "website", "DanaCita : Pinjaman Dana Cepat", null],
  [815, "website", "KitaRupiah", null],
  [816, "apkcombo", "Uang Kilat", null],
  [817, "softonic", "Fast Duit", null],
  [818, "website", "Loan Pal", null],
  [819, "website", "Rupiah Kas", null],
  [820, "website", "UANG MAJU", null],
  [821, "google_play", "PinjamAmanah - Perantara", null],
  [822, "website", "Kredit Praktis", null],
  [823, "website", "DANA EASY", null],
  [824, "website", "Pinjam Fun", null],
  [825, "website", "Gandeng : Pinjaman Rupiah Mudah", null],
  [826, "apksum", "Dana Tunai", null],
  [827, "softonic", "Uang Kilat - Pinjaman Dana", null],
  [828, "website", "AYO PINJAM", null],
  [829, "instagram", "AYO PINJAM ( TITISAN HUJAN)", null],
  [830, "website", "PINJAM UANG ONLINE", null],
  [831, "google_play", "Ada Dana-Pinjaman Cepat Loans", null],
  [832, "website", "HappyD", null],
  [833, "website", "DUIT PASTI", null],
  [834, "apkcombo", "Dana Online", null],
  [835, "sfile", "AKU CEPAT", null],
  [836, "website", "LoanPal – Pinjaman online", null],
  [837, "app_store", "UANG KILAT", null],
  [838, "softonic", "Danafix - Pinjaman Uang Online Kredit Tunai Cepat", null],
  [839, "website", "Dompet Pinjaman", null],
  [840, "website", "Maskas", null],
  [841, "website", "KreditKaya", null],
  [842, "website", "LoanPal", null],
  [843, "website", "Cepatcair", null],
  [844, "website", "Kaspin Go-Dana cair", null],
  [845, "website", "Free Loan", null],
  [846, "website", "Pinjam Fun", null],
  [847, "website", "KamiKaya", null],
  [848, "website", "PinjamLink", null],
  [849, "sfile", "Pinjaman Bintang", null],
  [850, "apkpure", "Dompet Kredit", null],
  [851, "google_play", "Dana Digital-Pinjaman Uang", null],
  [852, "website", "Duit Pasti/ Dana Kilat", null],
  [853, "website", "XTRA UANG NOW", null],
  [854, "app_store", "Credinex", null],
  [855, "link_shortener", "Rupiah Kas", null],
  [856, "website", "LOANPAL", null],
  [857, "website", "DANAKAMI", null],
  [858, "link_shortener", "SAYA KREDI", null],
  [859, "google_play", "Dana Cepat-Paylater & Pinjaman", null],
  [860, "website", "LOANPAL", null],
  [861, "google_play", "Kredit Kilat-Pinjaman Online", null],
  [862, "website", "Kredit Now", null],
  [863, "app_store", "Halogo", null],
  [864, "website", "KREDIT KAYA", null],
  [865, "google_play", "Ada Dana", null],
  [866, "google_play", "Uang Saya- Hitung Uang Tunai", null],
  [867, "website", "TOGU", null],
  [868, "website", "So Easy", null],
  [869, "uptodown", "UANG PLUS", null],
  [870, "website", "DANA KAMI", null],
  [871, "website", "Duit Pasti", null],
  [872, "website", "Ponsel Duit/ Modal Ku", null],
  [873, "google_play", "Dana Amanah", null],
  [874, "website", "Ponsel DUIT", null],
  [875, "website", "Dana Digital", null],
  [876, "softonic", "Tunai Instan", null],
  [877, "softonic", "TUNAI INSTAN DAN DANA SAKU", null],
  [878, "website", "POWERS", null],
  [879, "website", "KAYU API", null],
  [880, "google_play", "KREDIT KANCIL", null],
  [881, "app_store", "PRIMA KREDIT", null],
  [882, "google_play", "PINJAMPASTI (DOMPET AMAN)", null],
  [883, "website", "KREDIT KAYA (SUPER DANA)", null],
  [884, "website", "INDODANA", null],
  [885, "google_play", "MODALSIAP DAN DUITNOMPLOK", null],
  [886, "website", "MEKAR", null],
  [887, "instagram", "RUPIAH CAIR DOMPET PUAS", null],
  [888, "google_play", "UANG SAHABAT", null],
  [889, "instagram", "PINJAMAN PLANET", null],
  [890, "google_play", "UANG TRIP", null],
  [891, "website", "PT Media Grup ASIA", null],
  [892, "google_play", "TRUSTMINT", null],
  [893, "website", "DUIT PASTI", null],
  [894, "website", "RUPIAH BERSAMA / DANA FLEKSIBEL", null],
  [895, "website", "Modal Kilat - Pinjaman Online", null],
  [896, "website", "Kredit Ru piah / NUHA i-Tech", null],
  [897, "website", "Kredit Ru piah / NUHA i-Tech", null],
  [898, "website", "Pinjam Mudah", null],
  [899, "website", "Pinjam Tunai", null],
  [900, "website", "Dana Kami", null],
  [901, "website", "Dana Easy", null],
  [902, "website", "Dana Darurat", null],
  [903, "website", "KreditKancil", null],
  [904, "website", "PinjamPlus", null],
  [905, "website", "DanaKita", null],
  [906, "website", "Modal Kilat -Pinjaman Online", null],
  [907, "website", "Dana Easy", null],
  [908, "website", "UangKuNow / PT Super Pinjaman Indonesia", null],
  [909, "website", "UangKuNow / PT Super Pinjaman Indonesia", null],
  [910, "website", "UangKuNow / PT Super Pinjaman Indonesia", null],
  [911, "website", "KreditKancil", null],
  [912, "website", "KreditKancil", null],
  [913, "website", "PinjamPlus", null],
  [914, "website", "PinjamPlus", null],
  [915, "website", "Pinjam Kredit", null],
  [916, "website", "PT. Dana Cep at Indonesia", null],
  [917, "website", "Rupiah Cair", null],
  [918, "website", "Tunai Yuk", null],
  [919, "website", "PT. Dana Cep at Indonesia", null],
  [920, "website", "Dana Kami", null],
  [921, "website", "Kredit Kilat", null],
  [922, "website", "Rupiah Cair", null],
  [923, "website", "Dana Darurat", null],
  [924, "website", "Kredit Kilat", null],
  [925, "website", "Kredit Kilat", null],
  [926, "google_play", "Kredit Kancil", null],
  [927, "google_play", "PinjamanPlus", null],
  [928, "google_play", "Dana Cepat-Paylater & Pinjaman", null],
  [929, "google_play", "Kredit Kilat", null],
  [930, "instagram", "Dana Yuk", null],
  [931, "instagram", "Easy Dana", null],
  [932, "instagram", "Dana Baik", null],
  [933, "instagram", "Kredit Kilat", null],
  [934, "instagram", "Kredit Kilat", null],
  [935, "linkedin", "Kredit Kilat", null],
  [936, "linkedin", "Kredit Kilat", null],
  [937, "instagram", "Dana Digital", null],
  [938, "instagram", "Uang Indo", null],
  [939, "facebook", "Pinjam Mudah", null],
  [940, "instagram", "Pinjam Mudah", null],
  [941, "instagram", "Pinjam Tunai", null],
  [942, "instagram", "Pinjam Tunai", null],
  [943, "threads", "Dana Darurat", null],
  [944, "instagram", "UangKuNow / PT Super Pinjaman Indonesia", null],
  [945, "threads", "UangKuNow / PT Super Pinjaman Indonesia", null],
  [946, "instagram", "Kredit Kancil", null],
  [947, "instagram", "Pinjaman Plus", null],
  [948, "instagram", "Pinjaman Plus", null],
  [949, "instagram", "PT Dana Cepat Indonesia", null],
  [950, "instagram", "Kredit Kilat", null],
  [951, "instagram", "Rupiah Cair", null]
];

const dataPath = path.join(process.cwd(), 'data', 'illegal-lenders.json');
const current = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

current.illegal_lending = rawEntries.map(([no, channel, name, developer]) => ({
  no,
  url: `https://blocked-${no}.local`,
  host: `blocked-${no}.local`,
  channel,
  name,
  name_is_placeholder: false,
  developer,
  flags: []
}));

fs.writeFileSync(dataPath, JSON.stringify(current, null, 2));
console.log(`Populated ${current.illegal_lending.length} illegal lending rows to /data/illegal-lenders.json`);
